### PR TITLE
Free accounts support

### PR DESCRIPTION
**Pull request by devgianlu**
Looking forward to implement a ToS compliant support for free accounts. Previous discussion: https://github.com/librespot-org/librespot/issues/415 and https://github.com/librespot-org/librespot/issues/261.

**I'd like to remember that any use of free accounts until this PR is merged is not supported by the team.**

### CODE REVIEW

**Comment by polojoe** [comment]
No chance to get free account support?

**Comment by devgianlu** [comment]
> No chance to get free account support?

@polojoe Sorry for not noticing this before. Free accounts support is a very "tabu" feature that could get the project in real trouble. As long as it is for premium users only, Spotify doesn't lose anything because of us (we already pay a monthly subscription). If I were to include features for free accounts (ads, skip limit, ...), they could probably tell me I did so wrong and take down the project for making them lose money. Not to forget that implementing such features would take a lot of time. 

I hope you understand.

**Comment by SanderGit** [comment]
> > No chance to get free account support?
> 
>  Free accounts support is a very "tabu" feature that could get the project in real trouble. As long as it is for premium users only, Spotify doesn't lose anything because of us (we already pay a monthly subscription). If I were to include features for free accounts (ads, skip limit, ...), they could probably tell me I did so wrong and take down the project for making them lose money. 

I understand that Spotify has changed their policy for free accounts, and free users can stream to [Amazon, Sonos and Bose](https://www.reviewgeek.com/28328/spotify-free-users-can-now-stream-to-amazon-bose-and-sonos-smart-speakers/).
Does this change the situation?

**Comment by devgianlu** [comment]
> Does this change the situation?

No, because they have signed a partnership with Spotify that allows them to run the eSDK: https://developer.spotify.com/use-cases/hardware/home-audio/

**Pull request closed without merging**
