### PR TITLE
Changed image endpoint to i.scdn.co

### PR DESCRIPTION
**Pull request by uvjustin**

### CODE REVIEW

**Comment by devgianlu** [comment]
This shouldn't be an issue anymore because I found an endpoint that retrieves such URL.

**Comment by uvjustin** [comment]
Great, thanks.

**Comment by funtax** [comment]
@devgianlu The endpoint that retrieves the image-url isn't yet implemented, isn't it?

**Comment by devgianlu** [comment]
Yeah, it is on `dev`.

**Comment by funtax** [comment]
Cool thank you :)

**Pull request merged**
