### PR TITLE
Use apache-commons for Base64

### PR DESCRIPTION
**Pull request by funtax**
Some clients don't have java.util.Base64 (eg. Android). Please use a common Base64-library for Base64 de-/encoding.

### CODE REVIEW

**Comment by funtax** [comment]
Okay on older Android versions, apache-commons is shipped with Android but missing the decode64 method and others. I might push an update, please stay tuned.

**Comment by lkwg82** [comment]
Just out of curiosity, why should I use this lib with android when there is the spotify app?

**Comment by funtax** [comment]
I'm an Android developer and trying everything on this platform. I like the ability to be able to experiment with the library and not being forced to use the Spotify app but my own one 🙂

**Comment by zvertigo** [comment]
java.util.Base64 on Android is present since [API level 26](https://developer.android.com/reference/java/util/Base64.Encoder). Isn't it enough for now? It covers roughly a bit more than 70% of the current distribution according to [this page](https://gs.statcounter.com/android-version-market-share/mobile-tablet/worldwide) (which admittedly, is just the first result on a quick google search)

**Comment by funtax** [comment]
I just pushed a new update to this. Now I have removed the apache-common-dependency and added an apache-licensed Base64.java into the utils-package so it doesn't depend on any external resources.
--------
Some more background-information for this problem:
I want to allow users to re-use (old) Android-devices so they can be connected via cable to their AV-receivers to be compatible with Spotify-Connect.

In my case I am using an old Nexus 5 with a broken screen running Android 5 which doesn't have the java.util.Base64 shipped.

There's no Google Play or Spotify-app installed on this device.
Additionally, the Spotify-app requires you to be logged-in but I just want to run this app via autostart and rely on ZeroConf.

I could of course run librespot on a Raspberry-PI for this, but I have five old devices so I had the idea to re-use them for this :)

**Comment by funtax** [comment]
Okay never mind, I will close this PR for the moment. This library contains more stuff driving it incompatible with Android <8 (eg. usage of Lambdas), so I have to target a later Android-version ;-)

**Pull request closed without merging**
